// src/utils/constants.js

export const availableTags = ["ภาษี", "พรบ.", "ตรอ."];

export const vehicleTypes = ["รย.1", "รย.2", "รย.3", "รย.12", "รย.17"];

export const carBrands = [
  'Abarth', 'Acura', 'Aeolus', 'Aiways', 'Aion', 'AJS', 'Alfa Romeo', 'Alpine', 'Alpina', 'Alvis', 
  'AMC', 'Amilcar', 'Amphicar', 'Apollo', 'Aprilia', 'Ariel', 'Asia Motors', 'Aston Martin', 
  'Auburn', 'Audi', 'Aurus', 'Austin', 'Austin-Healey', 'Autobianchi', 'Auto Union', 'Autozam', 'Avatr',
  'BAC', 'BAIC', 'Bajaj', 'Baojun', 'Benelli', 'Bentley', 'Bertone', 'Beta', 'Bimota', 'Bitter', 
  'Bizzarrini', 'BMW', 'BMW Motorrad', 'Borgward', 'Boss Hoss', 'Bristol', 'BSA', 'Buell', 
  'Bugatti', 'Buick', 'Bultaco', 'BYD',
  'Cadillac', 'Cagiva', 'Caterham', 'CCM', 'CFMoto', 'Chaika', 'Changan', 'Checker', 'Chery', 
  'Chevrolet', 'Chrysler', 'Cisitalia', 'Citroën', 'Continental', 'Cord', 'Crocker', 'Crosley', 'Cupra',
  'Dacia', 'Daewoo', 'DAF', 'Daihatsu', 'Daimler', 'Datsun', 'De Tomaso', 'Deepal', 'DeLorean', 
  'Denza', 'DeSoto', 'Dodge', 'Dongfeng', 'Donkervoort', 'DR Automobiles', 'DS Automobiles', 'Ducati', 'Duesenberg',
  'Eagle', 'Edsel', 'Efini', 'Excelsior', 'Exeed',
  'Facel Vega', 'Fang Cheng Bao', 'Fantic', 'Faraday Future', 'FAW', 'Ferrari', 'Fiat', 'Fisker', 
  'Force Motors', 'Ford', 'Forthing', 'Foton', 'Frazer', 'Fuso',
  'GAC', 'GasGas', 'GAZ', 'Geely', 'Genesis', 'Geo', 'Gilera', 'Ginetta', 'GMC', 'Gordon Murray', 
  'GPX', 'Great Wall', 'Gumpert',
  'Harley-Davidson', 'Haval', 'Hennessey', 'Hero MotoCorp', 'Hillman', 'Hindustan', 'Hino', 
  'HiPhi', 'Holden', 'Honda', 'Hongqi', 'Horch', 'Horex', 'HSV', 'Hudson', 'Hummer', 
  'Humber', 'Husqvarna', 'Hyundai', 'Hyosung',
  'iCar', 'Indian Motorcycle', 'Ineos', 'Infiniti', 'Innocenti', 'Intermeccanica', 'International Harvester', 
  'Isdera', 'Iso', 'Isuzu', 'Italdesign', 'Italjet',
  'JAC', 'Jaecoo', 'Jaguar', 'Janus', 'Jawa', 'Jeep', 'Jensen', 'Jetour', 'JMC', 'Jowett',
  'Kaicene', 'Kaiser', 'Karma', 'Kawasaki', 'Keeway', 'KG Mobility', 'Kia', 'Koenigsegg', 'Kove', 'KTM', 'Kymco',
  'Lada', 'Lagonda', 'Lamborghini', 'Lambretta', 'Lancia', 'Land Rover', 'Laverda', 'Leapmotor', 
  'Lexus', 'Li Auto', 'Lifan', 'Ligier', 'Lincoln', 'Lotus', 'Lucid', 'Lynk & Co',
  'Mahindra', 'Malaguti', 'MAN', 'Marcos', 'Maruti Suzuki', 'Maserati', 'Matchless', 'Matra', 'Maxus', 
  'Maybach', 'Mazda', 'Mazzanti', 'McLaren', 'Mercedes-Benz', 'Mercury', 'Merkur', 'Messerschmitt', 
  'MG', 'Microcar', 'Mine Mobility', 'Mini', 'Mitsubishi', 'Mitsuoka', 'Montesa', 'Morgan', 'Morris', 
  'Moskvitch', 'Moto Guzzi', 'Mutt', 'MV Agusta',
  'Nash', 'Neta', 'Neoplan', 'Nio', 'Nissan', 'Noble', 'Norton', 'NSU',
  'Oakland', 'Oldsmobile', 'Omoda', 'Opel', 'Ora', 'Osca',
  'Packard', 'Pagani', 'Panhard', 'Panoz', 'Perodua', 'Peugeot', 'Peugeot Motocycles', 'Piaggio', 
  'Pierce-Arrow', 'Pininfarina', 'Plymouth', 'Poer', 'Polestar', 'Pontiac', 'Porsche', 'Prince', 'Proton',
  'QJ Motor',
  'Radical', 'Ram', 'Rambler', 'Reliant', 'Renault', 'Renault Korea', 'Rieju', 'Riley', 'Rimac', 
  'Rivian', 'Roewe', 'Rolls-Royce', 'Rossion', 'Rover', 'Royal Enfield', 'Ruf', 'Russo-Balt', 'Ryuka',
  'Saab', 'Saleen', 'Saturn', 'Scion', 'Scomadi', 'Seat', 'Seres', 'Shelby', 'Shineray', 'Siata', 
  'Simca', 'Singer', 'Skoda', 'Smart', 'Solar', 'Spyker', 'SsangYong', 'SSC', 'Stallions', 'Studebaker', 
  'Stutz', 'Subaru', 'Sunbeam', 'Suzuki', 'SYM',
  'Talbot', 'Tank', 'Tata', 'Tatra', 'Tesla', 'Thairung', 'Tiger', 'Togg', 'Tommykaira', 'Toyota', 
  'Trabant', 'Traxxas', 'Triumph', 'Trumpchi', 'Tucker', 'TVR', 'TVS',
  'UAZ', 'UD Trucks',
  'Vanden Plas', 'Vauxhall', 'Velocette', 'Venturi', 'Vera', 'Vespa', 'Victory', 'VinFast', 'Vincent', 
  'Voge', 'Voisin', 'Volga', 'Volkswagen', 'Volvo', 'Voyah',
  'W Motors', 'Wanderer', 'Wartburg', 'Weltmeister', 'Wey', 'Wiesmann', 'Willys', 'Wolseley', 'Wuling',
  'Xiaomi', 'Xpeng',
  'Yamaha', 'Yangwang', 'Yezdi',
  'Zagato', 'ZAZ', 'Zeekr', 'Zenvo', 'Zero Motorcycles', 'ZIL', 'Zongshen', 'Zontes', 'Zündapp'
];